[[packages]]
github = "https://github.com/rokubop/talon-ui-elements"

[[packages]]
github = "https://github.com/rokubop/talon-pack"

[[packages]]
github = "https://github.com/rokubop/talon-parrot-tester"

[[packages]]
github = "https://github.com/rokubop/talon-rig-core"

[[packages]]
github = "https://github.com/rokubop/talon-mouse-rig"

[[packages]]
github = "https://github.com/rokubop/talon-gamepad-rig"

[[packages]]
github = "https://github.com/rokubop/talon-input-map"

[[packages]]
github = "https://github.com/rokubop/talon-noise-map"

[[packages]]
github = "https://github.com/rokubop/talon-pynput"

[[packages]]
github = "https://github.com/rokubop/talon-parrot-rig"

# [[packages]]
# # # github = "https://github.com/rokubop/talon-face-tester"
# path = "../talon-face-tester"

# [[packages]]
# path = "../talon-parrot-roku-model"

# [[packages]]
# # # github = "https://github.com/rokubop/talon-obs-integration"
# path = "../talon-obs-integration"
